"""Generate the teaching notebooks for the Geography + AI collection.

Run from the repository root:
    python _build_notebooks.py

Output files are written to ./notebooks/.
"""
from __future__ import annotations
import json
import uuid
from pathlib import Path


def make_notebook(cells: list[dict]) -> dict:
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3.11"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def md(*lines: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "id": uuid.uuid4().hex[:12],
            "source": [line + "\n" for line in lines]}


def code(*lines: str) -> dict:
    return {"cell_type": "code", "execution_count": None, "metadata": {},
            "id": uuid.uuid4().hex[:12], "outputs": [],
            "source": [line + "\n" for line in lines]}


# ---------------------------------------------------------------------------
# Notebook 1: Classifying storm rainfall patterns with machine learning
# ---------------------------------------------------------------------------
nb1 = make_notebook([
    md(
        "# Classifying Storm Rainfall Patterns with Machine Learning",
        "",
        "*Geography + AI Teaching Notebooks · 1 of 3*",
        "",
        "Storms do not just differ in *how much* rain they bring — they differ in",
        "*how that rain is arranged in space*. A compact, intense core and a broad,",
        "gentle shield can deliver the same total rainfall but produce very",
        "different flood responses downstream.",
        "",
        "This notebook is a teaching module on **unsupervised machine learning**.",
        "It shows how to take a set of rainfall fields, reduce their dimensionality,",
        "and let an algorithm discover recurring spatial *regimes* — all with",
        "synthetic, reproducible data that runs on any laptop.",
        "",
        "**What students practise here**",
        "1. Generating and visualising gridded spatial data.",
        "2. Reducing dimensionality with Principal Component Analysis.",
        "3. Clustering with k-means.",
        "4. Interpreting cluster centroids as physically meaningful patterns.",
        "5. Connecting an abstract method to a real geographic question.",
    ),
    code(
        "import numpy as np",
        "import matplotlib.pyplot as plt",
        "from sklearn.decomposition import PCA",
        "from sklearn.cluster import KMeans",
        "from sklearn.preprocessing import StandardScaler",
        "",
        "rng = np.random.default_rng(42)",
        "GRID = 32        # 32x32 grid representing a radar rainfall patch",
        "N_EVENTS = 200   # number of synthetic storm events",
    ),
    md(
        "## 1. Synthetic storm rainfall fields",
        "",
        "We simulate four canonical rainfall structures. In a real course, students",
        "would later swap in archived radar data — the workflow is identical.",
        "",
        "- **Concentric** — a strong, roughly circular core (think of a mature",
        "  cyclone eyewall).",
        "- **Asymmetric** — rain concentrated on one side of the storm.",
        "- **Distributed** — a broad shield of lower-intensity rain.",
        "- **Multi-cell** — several discrete convective maxima.",
    ),
    code(
        "def gaussian_blob(grid, center, sigma, peak):",
        "    y, x = np.mgrid[0:grid, 0:grid]",
        "    r2 = (x - center[0])**2 + (y - center[1])**2",
        "    return peak * np.exp(-r2 / (2 * sigma**2))",
        "",
        "def make_concentric(rng):",
        "    field = gaussian_blob(GRID, (16, 16), 4, 60)",
        "    return field + rng.normal(0, 2, (GRID, GRID))",
        "",
        "def make_asymmetric(rng):",
        "    field = gaussian_blob(GRID, (10, 16), 5, 70)",
        "    field += gaussian_blob(GRID, (22, 16), 3, 25)",
        "    return field + rng.normal(0, 2, (GRID, GRID))",
        "",
        "def make_distributed(rng):",
        "    field = gaussian_blob(GRID, (12, 14), 9, 30)",
        "    field += gaussian_blob(GRID, (22, 20), 8, 22)",
        "    return field + rng.normal(0, 3, (GRID, GRID))",
        "",
        "def make_multicell(rng):",
        "    field = np.zeros((GRID, GRID))",
        "    for _ in range(4):",
        "        cx, cy = rng.integers(6, 26, size=2)",
        "        field += gaussian_blob(GRID, (cx, cy), 2.5, rng.uniform(35, 55))",
        "    return field + rng.normal(0, 2, (GRID, GRID))",
        "",
        "GENERATORS = [make_concentric, make_asymmetric, make_distributed, make_multicell]",
        "labels = rng.integers(0, len(GENERATORS), size=N_EVENTS)",
        "events = np.stack([GENERATORS[k](rng) for k in labels])",
        "events = np.clip(events, 0, None)  # rainfall cannot be negative",
        "print(f'Generated a tensor of shape {events.shape}')",
    ),
    code(
        "fig, axes = plt.subplots(2, 4, figsize=(12, 6))",
        "titles = ['Concentric', 'Asymmetric', 'Distributed', 'Multi-cell']",
        "for col in range(4):",
        "    for row in range(2):",
        "        idx = np.where(labels == col)[0][row]",
        "        ax = axes[row, col]",
        "        ax.imshow(events[idx], cmap='Blues', vmin=0, vmax=80)",
        "        if row == 0:",
        "            ax.set_title(titles[col])",
        "        ax.set_xticks([]); ax.set_yticks([])",
        "fig.suptitle('Eight example synthetic rainfall fields', y=1.02)",
        "plt.tight_layout(); plt.show()",
    ),
    md(
        "## 2. Dimensionality reduction with PCA",
        "",
        "Each 32x32 field is 1024 numbers. PCA finds the handful of combined",
        "patterns ('principal components') that capture most of the variation,",
        "so that later steps work in a much smaller, less noisy space.",
    ),
    code(
        "X = events.reshape(N_EVENTS, -1)",
        "Xs = StandardScaler().fit_transform(X)",
        "",
        "pca = PCA(n_components=10, random_state=0)",
        "Z = pca.fit_transform(Xs)",
        "print('Explained variance ratio:', np.round(pca.explained_variance_ratio_, 3))",
    ),
    code(
        "plt.figure(figsize=(6, 4))",
        "plt.plot(np.cumsum(pca.explained_variance_ratio_), marker='o')",
        "plt.xlabel('Principal component index')",
        "plt.ylabel('Cumulative explained variance')",
        "plt.title('How much pattern each component captures')",
        "plt.grid(alpha=0.3); plt.show()",
    ),
    md(
        "## 3. Clustering the storms",
        "",
        "k-means groups the events in the reduced PCA space. In a real study we",
        "would not know the 'true' labels — the clusters are interpreted as",
        "*emergent* rainfall regimes that the data reveal on their own.",
    ),
    code(
        "kmeans = KMeans(n_clusters=4, n_init=20, random_state=0)",
        "clusters = kmeans.fit_predict(Z)",
        "",
        "fig, ax = plt.subplots(figsize=(6, 5))",
        "ax.scatter(Z[:, 0], Z[:, 1], c=clusters, cmap='tab10', s=22, alpha=0.8)",
        "ax.set_xlabel('PC 1'); ax.set_ylabel('PC 2')",
        "ax.set_title('k-means clusters in PCA space')",
        "plt.tight_layout(); plt.show()",
    ),
    code(
        "fig, axes = plt.subplots(1, 4, figsize=(13, 3.5))",
        "for k in range(4):",
        "    mean_field = events[clusters == k].mean(axis=0)",
        "    axes[k].imshow(mean_field, cmap='Blues', vmin=0, vmax=80)",
        "    axes[k].set_title(f'Cluster {k}\\nn={(clusters == k).sum()}')",
        "    axes[k].set_xticks([]); axes[k].set_yticks([])",
        "fig.suptitle('Cluster centroids — the rainfall regimes the data revealed', y=1.05)",
        "plt.tight_layout(); plt.show()",
    ),
    md(
        "## 4. Why this matters geographically",
        "",
        "Spatial structure, not just total rainfall, shapes how a landscape",
        "responds. The same clustering can become a categorical input to a",
        "rainfall-runoff model, helping with:",
        "",
        "- **Reservoir and flood-warning operations** — anticipating the response",
        "  to an approaching storm of a known *type*.",
        "- **Sediment and erosion estimates** — different storm regimes mobilise",
        "  very different amounts of material.",
        "- **Climate analysis** — tracking whether certain storm types are",
        "  becoming more frequent.",
        "",
        "### Suggested extensions for students",
        "",
        "1. Replace the synthetic data with an open radar archive.",
        "2. Try other clusterers (Gaussian Mixture, HDBSCAN) and compare.",
        "3. Vary the number of clusters and discuss how to choose it.",
        "4. Use SHAP or feature importance to interpret a supervised model that",
        "   predicts a flood metric from the storm type.",
    ),
])

# ---------------------------------------------------------------------------
# Notebook 2: Watershed analysis from a DEM with pure Python
# ---------------------------------------------------------------------------
nb2 = make_notebook([
    md(
        "# Watershed Analysis from a DEM with Pure Python",
        "",
        "*Geography + AI Teaching Notebooks · 2 of 3*",
        "",
        "Geographic Information Systems hide a lot of hydrology behind a few menu",
        "clicks. This notebook opens the black box: it derives a stream network",
        "and several terrain metrics **from a digital elevation model (DEM) using",
        "nothing but NumPy**, so students can see exactly what each step does.",
        "",
        "Everything runs on a synthetic DEM, so the notebook is fully",
        "reproducible. Swapping in a real DEM (e.g. an open national elevation",
        "dataset) requires changing only the first code cell.",
        "",
        "**What students practise here**",
        "1. Reading and visualising a DEM.",
        "2. The D8 flow-direction algorithm.",
        "3. Flow accumulation and stream-network extraction.",
        "4. The hypsometric curve as a descriptor of basin form.",
        "5. The Topographic Wetness Index.",
    ),
    code(
        "import numpy as np",
        "import matplotlib.pyplot as plt",
        "from scipy.ndimage import gaussian_filter",
        "",
        "rng = np.random.default_rng(7)",
        "GRID = 200",
        "",
        "# A synthetic DEM: a tilted plane plus smoothed random relief.",
        "yy, xx = np.mgrid[0:GRID, 0:GRID]",
        "tilt = 1800 - 0.6 * xx - 0.5 * yy   # highland in one corner",
        "relief = gaussian_filter(rng.normal(0, 60, (GRID, GRID)), sigma=5)",
        "dem = np.clip(tilt + relief, 0, None)",
        "print(f'DEM elevation range: {dem.min():.0f}-{dem.max():.0f} m')",
    ),
    code(
        "fig, ax = plt.subplots(figsize=(6, 5))",
        "im = ax.imshow(dem, cmap='terrain', origin='lower')",
        "plt.colorbar(im, ax=ax, label='Elevation (m)')",
        "ax.set_title('Synthetic digital elevation model')",
        "ax.set_xticks([]); ax.set_yticks([])",
        "plt.tight_layout(); plt.show()",
    ),
    md(
        "## 1. Flow direction (the D8 algorithm)",
        "",
        "D8 assigns each cell the direction of its steepest-descent neighbour —",
        "one of eight compass directions. It is the foundation of almost every",
        "GIS hydrology tool.",
    ),
    code(
        "def d8_flow_direction(dem):",
        "    di = np.array([-1, -1, -1,  0, 0,  1, 1, 1])",
        "    dj = np.array([-1,  0,  1, -1, 1, -1, 0, 1])",
        "    dist = np.sqrt(di**2 + dj**2)",
        "    direction = np.zeros(dem.shape, dtype=np.int8)",
        "    slope = np.zeros(dem.shape)",
        "    for k in range(8):",
        "        shifted = np.roll(np.roll(dem, -di[k], axis=0), -dj[k], axis=1)",
        "        s = (dem - shifted) / dist[k]",
        "        mask = s > slope",
        "        slope[mask] = s[mask]",
        "        direction[mask] = k + 1",
        "    return direction, slope",
        "",
        "direction, slope = d8_flow_direction(dem)",
        "print('Flow direction grid computed.')",
    ),
    md(
        "## 2. Flow accumulation",
        "",
        "Route one unit of water through every cell repeatedly. Cells that many",
        "others drain into accumulate large values — these are the channels.",
    ),
    code(
        "def flow_accumulation(direction, n_iter=40):",
        "    di = np.array([0, -1, -1, -1,  0, 0,  1, 1, 1])",
        "    dj = np.array([0, -1,  0,  1, -1, 1, -1, 0, 1])",
        "    acc = np.ones(direction.shape)",
        "    for _ in range(n_iter):",
        "        new_acc = np.ones(direction.shape)",
        "        for k in range(1, 9):",
        "            shifted = np.roll(np.roll(acc, di[k], axis=0), dj[k], axis=1)",
        "            inflow = (np.roll(np.roll(direction, di[k], axis=0), dj[k], axis=1) == k)",
        "            new_acc += shifted * inflow",
        "        acc = new_acc",
        "    return acc",
        "",
        "acc = flow_accumulation(direction)",
    ),
    code(
        "fig, ax = plt.subplots(figsize=(6, 5))",
        "im = ax.imshow(np.log1p(acc), cmap='Blues', origin='lower')",
        "plt.colorbar(im, ax=ax, label='log(accumulated cells)')",
        "ax.set_title('Flow accumulation (log scale)')",
        "ax.set_xticks([]); ax.set_yticks([])",
        "plt.tight_layout(); plt.show()",
    ),
    md(
        "## 3. Extracting the stream network",
        "",
        "Cells whose accumulation exceeds a threshold are treated as streams.",
        "The threshold is a modelling choice — students should experiment with it.",
    ),
    code(
        "threshold = np.percentile(acc, 96)",
        "stream = acc > threshold",
        "",
        "fig, ax = plt.subplots(figsize=(6, 5))",
        "ax.imshow(dem, cmap='terrain', origin='lower', alpha=0.7)",
        "ax.imshow(np.where(stream, 1, np.nan), cmap='Blues', origin='lower', alpha=0.9)",
        "ax.set_title('Extracted stream network')",
        "ax.set_xticks([]); ax.set_yticks([])",
        "plt.tight_layout(); plt.show()",
    ),
    md(
        "## 4. The hypsometric curve",
        "",
        "The hypsometric curve plots elevation against the fraction of the basin",
        "lying above it. Its shape is a classic indicator of how 'young' or",
        "'mature' a landscape is (Strahler, 1952).",
    ),
    code(
        "elevations = np.sort(dem.flatten())",
        "cum_area = np.arange(elevations.size, 0, -1) / elevations.size",
        "norm_z = (elevations - elevations.min()) / (elevations.max() - elevations.min())",
        "",
        "fig, ax = plt.subplots(figsize=(5, 4))",
        "ax.plot(cum_area, norm_z, lw=2)",
        "ax.set_xlabel('Cumulative area fraction')",
        "ax.set_ylabel('Normalised elevation')",
        "ax.set_title('Hypsometric curve')",
        "ax.grid(alpha=0.3)",
        "plt.tight_layout(); plt.show()",
    ),
    md(
        "## 5. The Topographic Wetness Index",
        "",
        "TWI = ln(a / tan β) combines upslope area with local slope to predict",
        "where soils stay wet. It is a quick first guess for saturation-prone",
        "ground and riparian zones.",
    ),
    code(
        "tan_beta = np.tan(np.arctan(slope) + 1e-6)",
        "twi = np.log((acc + 1) / (tan_beta + 1e-6))",
        "",
        "fig, ax = plt.subplots(figsize=(6, 5))",
        "im = ax.imshow(twi, cmap='YlGnBu', origin='lower')",
        "plt.colorbar(im, ax=ax, label='TWI')",
        "ax.set_title('Topographic Wetness Index')",
        "ax.set_xticks([]); ax.set_yticks([])",
        "plt.tight_layout(); plt.show()",
    ),
    md(
        "## Wrap-up",
        "",
        "Each step above replaces several GIS menu clicks with a few transparent",
        "lines of NumPy. Replacing the synthetic DEM with a real one — from any",
        "open national elevation dataset — turns this notebook into the starting",
        "point for a genuine watershed project.",
        "",
        "### Suggested extensions for students",
        "",
        "1. Load a real DEM with `rioxarray` and re-run every cell.",
        "2. Delineate the watershed draining to a chosen outlet cell.",
        "3. Compare the hypsometric curve of two contrasting basins.",
        "4. Overlay a satellite-derived water index on the extracted network.",
    ),
])

# ---------------------------------------------------------------------------
# Notebook 3: Generative AI as a geography-teaching companion
# ---------------------------------------------------------------------------
nb3 = make_notebook([
    md(
        "# Generative AI as a Geography-Teaching Companion",
        "",
        "*Geography + AI Teaching Notebooks · 3 of 3*",
        "",
        "This notebook is a small **pattern library** for using generative AI in",
        "geography teaching. The goal is not to hand thinking over to AI, but to",
        "use it as a structured assistant — and to train students to read its",
        "output critically.",
        "",
        "Three reusable patterns are shown:",
        "",
        "1. **Concept Tutor** — a constrained prompt that makes the model *teach*",
        "   rather than merely answer.",
        "2. **Map Reading** — a workflow for vision-capable models to extract",
        "   structured information from a historical map.",
        "3. **Field-Interview Pipeline** — speech-to-text plus structured",
        "   summarisation for fieldwork notes.",
        "",
        "Every cell runs with stubbed responses, so the notebook is reproducible",
        "without API keys. Real API calls are shown but commented out.",
    ),
    code(
        "import json, textwrap",
        "from dataclasses import dataclass",
        "",
        "# A stubbed responder so the notebook runs without API access.",
        "def call_llm(prompt: str, model: str = 'stub') -> str:",
        "    if model == 'stub':",
        "        return (",
        "            'ONE-LINE DEFINITION: Transit time is the time water takes to'",
        "            ' travel through a catchment from input to output.\\n'",
        "            'EXAMPLE: After a storm, rain landing on a hillslope may take'",
        "            ' weeks to months to reach the stream as slow subsurface flow.\\n'",
        "            'FOLLOW-UP QUESTIONS: (1) How would a drought change transit'",
        "            ' time? (2) Why can two catchments of equal size have very'",
        "            ' different transit times?'",
        "        )",
        "    # Real usage (commented):",
        "    # import openai",
        "    # return openai.ChatCompletion.create(...)['choices'][0]['message']['content']",
        "    return ''",
    ),
    md(
        "## Pattern 1 · Concept Tutor",
        "",
        "The system prompt forces the model to answer in three labelled parts: a",
        "one-line definition, a concrete example, and two follow-up questions.",
        "This turns a plain answer into a small teaching interaction.",
    ),
    code(
        "TUTOR_SYSTEM = textwrap.dedent('''\\",
        "    You are a geography teaching assistant.",
        "    For every question, respond with exactly three labelled parts:",
        "    (1) ONE-LINE DEFINITION",
        "    (2) A CONCRETE EXAMPLE",
        "    (3) TWO FOLLOW-UP QUESTIONS for the student to think about.",
        "    Use plain prose. Do not exceed 120 words.''')",
        "",
        "student_q = 'What is the transit time of water in a catchment?'",
        "answer = call_llm(TUTOR_SYSTEM + '\\n\\nStudent: ' + student_q)",
        "print(answer)",
    ),
    md(
        "**In class.** The model output is *one* example answer. Students compare",
        "it with the textbook, mark anything inaccurate, and judge whether the",
        "example really fits. The grade rewards the critique, not the AI.",
    ),
    md(
        "## Pattern 2 · Reading a historical map with a vision model",
        "",
        "Vision-capable models can help transcribe old maps, but their output",
        "must be checked. Forcing the answer into JSON makes it easy to compare",
        "with the original and to load into a GIS.",
    ),
    code(
        "MAP_PROMPT = textwrap.dedent('''\\",
        "    You are reading a historical topographic map sheet. Return JSON with:",
        "    - sheet_id (string)",
        "    - place_names (list of {name, type})",
        "    - waterways (list of {name, role})",
        "    - uncertain_items (list of anything you could not read confidently)",
        "    Be conservative: if unsure, put the item in uncertain_items.''')",
        "",
        "# Real request (commented):",
        "# response = openai.ChatCompletion.create(",
        "#     model='gpt-4-vision', messages=[",
        "#         {'role': 'system', 'content': MAP_PROMPT},",
        "#         {'role': 'user', 'content': [{'type': 'image_url',",
        "#                                       'image_url': 'file://map_sheet.jpg'}]}])",
        "",
        "stub_response = {",
        "    'sheet_id': 'historical_sheet_excerpt',",
        "    'place_names': [",
        "        {'name': 'Riverside Village', 'type': 'settlement'},",
        "        {'name': 'Old Mill', 'type': 'landmark'},",
        "    ],",
        "    'waterways': [",
        "        {'name': 'Main River', 'role': 'primary channel'},",
        "        {'name': 'unnamed channel', 'role': 'possible former course'},",
        "    ],",
        "    'uncertain_items': ['a faint label near the map edge'],",
        "}",
        "print(json.dumps(stub_response, indent=2, ensure_ascii=False))",
    ),
    md(
        "**In class.** Students compare the JSON with the original map. The",
        "exercise builds three skills at once: map literacy, critical evaluation",
        "of AI output, and structured-data thinking.",
    ),
    md(
        "## Pattern 3 · A field-interview pipeline",
        "",
        "During fieldwork, students often record short interviews with local",
        "residents. The pipeline below converts speech to text and then asks an",
        "LLM for a structured field summary — always staying close to the",
        "speaker's own words.",
    ),
    code(
        "@dataclass",
        "class InterviewSummary:",
        "    interviewee_role: str",
        "    key_themes: list[str]",
        "    quoted_passages: list[str]",
        "    open_questions: list[str]",
        "",
        "STRUCTURED_PROMPT = textwrap.dedent('''\\",
        "    Read the interview transcript and produce JSON with: interviewee_role,",
        "    key_themes (3-5), quoted_passages (verbatim), open_questions.",
        "    Stay close to the speaker. Do not invent information.''')",
        "",
        "sample_transcript = (",
        "    'We have farmed this land for three generations. The irrigation water'",
        "    ' used to arrive on the same date every year, but lately the schedule'",
        "    ' shifts with the reservoir level, so in dry years we plant less.'",
        ")",
        "# response = call_llm(STRUCTURED_PROMPT + '\\n\\n' + sample_transcript)",
        "stub = InterviewSummary(",
        "    interviewee_role='Smallholder farmer',",
        "    key_themes=['Irrigation scheduling', 'Reservoir-driven variability',",
        "                'Multi-generational farming'],",
        "    quoted_passages=['in dry years we plant less'],",
        "    open_questions=['How is the irrigation schedule communicated to farmers today?'],",
        ")",
        "print(stub)",
    ),
    md(
        "## Reflection: where AI fits in the curriculum",
        "",
        "| Pattern | Role of the AI | Student learning target |",
        "|---|---|---|",
        "| Concept Tutor | Scaffold | Comparison and critique |",
        "| Map Reading | Extractor | Map literacy + data thinking |",
        "| Field-Interview Pipeline | Stenographer | Field method |",
        "",
        "In every pattern, **the AI's output is a draft, not a verdict.** Students",
        "are assessed on how they evaluate, correct, and extend that draft —",
        "never on whether the AI happened to be right.",
        "",
        "This pattern library is open and will grow as more classroom-tested",
        "uses of AI in geography teaching are added.",
    ),
])


def main():
    here = Path(__file__).parent
    out = here / "notebooks"
    out.mkdir(exist_ok=True)
    for name, nb in [
        ("01_rainfall_pattern_ml.ipynb", nb1),
        ("02_watershed_gis_python.ipynb", nb2),
        ("03_ai_in_geography_teaching.ipynb", nb3),
    ]:
        (out / name).write_text(json.dumps(nb, ensure_ascii=False, indent=1),
                                encoding="utf-8")
        print(f"wrote {out / name}")


if __name__ == "__main__":
    main()
